module.exports = {
    "avalanche": "AVAX",
    "binance coin": "BNB",
    "binance usd": "BUSD",
    "bitcoin cash": "BCH",
    "bitcoin": "BTC",
    "bnb": "BNB",
    "cardano": "ADA",
    "chainlink": "LINK",
    "dogecoin": "DOGE",
    "eos": "EOS",
    "ethereum": "ETH",
    "filecoin": "FIL",
    "iota": "MIOTA",
    "neo": "NEO",
    "polkadot": "DOT",
    "polygon": "MATIC",
    "shiba inu": "SHIB",
    "solana": "SOL",
    "stellar": "XLM",
    "terra": "LUNA",
    "tether": "USDT",
    "tezos": "XTZ",
    "tron": "TRX",
    "uniswap": "UNI",
    "usd coin": "USDC",
    "vechain": "VET",
    "xrp": "XRP",
}